# Generated by Django 3.0.6 on 2020-06-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(max_length=64)),
                ('small_price', models.FloatField(max_length=10)),
                ('large_price', models.FloatField(max_length=10)),
            ],
        ),
    ]
