# Generated by Django 3.0.6 on 2020-06-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinnerplatters_pastas_salads_sicpizza_subextras_subs_toppings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatters',
        ),
    ]
