# Generated by Django 3.0.6 on 2020-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_dinnerplatters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platter', models.CharField(max_length=64)),
                ('small_price', models.FloatField(max_length=10)),
                ('large_price', models.FloatField(max_length=10)),
            ],
        ),
    ]
