# Generated by Django 3.0.6 on 2020-06-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dinnerplatters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegPizza',
            new_name='RegPizzas',
        ),
        migrations.RenameModel(
            old_name='SicPizza',
            new_name='SicPizzas',
        ),
    ]
