# Generated by Django 3.0.6 on 2020-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_categories_extras_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatters',
        ),
        migrations.DeleteModel(
            name='Pastas',
        ),
        migrations.DeleteModel(
            name='RegPizzas',
        ),
        migrations.DeleteModel(
            name='Salads',
        ),
        migrations.DeleteModel(
            name='SicPizzas',
        ),
        migrations.DeleteModel(
            name='SubExtras',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.AddField(
            model_name='items',
            name='set_price',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
