# Generated by Django 3.0.6 on 2020-06-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200605_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='name',
            new_name='extra',
        ),
    ]
