# Generated by Django 3.0.6 on 2020-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200605_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='category',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='item',
        ),
        migrations.AddField(
            model_name='items',
            name='extras',
            field=models.ManyToManyField(to='orders.Extras'),
        ),
    ]
