# Generated by Django 3.0.6 on 2020-06-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200606_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Toppings',
        ),
    ]
