# Generated by Django 3.0.6 on 2020-06-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_delete_category_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Categories')),
            ],
        ),
    ]
