# Generated by Django 3.0.6 on 2020-06-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0016_category_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
