# Generated by Django 3.0.6 on 2020-06-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0017_auto_20200607_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Toppings',
            new_name='Category_Topping',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Item_Toppings',
            new_name='Item_Topping',
        ),
    ]
