# Generated by Django 3.0.6 on 2020-06-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200620_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_topping', models.ManyToManyField(related_name='cat_topping', to='orders.Category_Topping')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Item')),
                ('item_topping', models.ManyToManyField(related_name='item_topping', to='orders.Item_Topping')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Ticket'),
        ),
    ]
