# Generated by Django 3.0.6 on 2020-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200622_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(to='orders.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cat_topping',
            field=models.ManyToManyField(blank=True, related_name='cat_topping', to='orders.Category_Topping'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item_topping',
            field=models.ManyToManyField(blank=True, related_name='item_topping', to='orders.Item_Topping'),
        ),
    ]
