# Generated by Django 3.0.6 on 2020-06-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200623_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='item_price',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large'), ('ST', 'Set')], default='SM', max_length=2),
        ),
    ]
