# Generated by Django 3.0.6 on 2020-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200623_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_price',
            name='topping_count',
            field=models.IntegerField(default=0),
        ),
    ]
