# Generated by Django 3.0.6 on 2020-06-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_item_price_topping_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cat_topping',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='item_topping',
        ),
        migrations.AlterField(
            model_name='item_price',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='orders.Item'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
