# Generated by Django 3.0.6 on 2020-06-23 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0032_auto_20200623_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_topping', models.ManyToManyField(to='orders.Category_Topping')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Item')),
                ('item_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Item_Price')),
                ('item_topping', models.ManyToManyField(to='orders.Item_Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('CA', 'Carted'), ('PL', 'Placed'), ('PR', 'Preparing'), ('RE', 'Ready'), ('DE', 'Delivered'), ('CC', 'Cancelled by customer'), ('CR', 'Cancelled by restaurant')], default='CA', max_length=2)),
                ('order', models.ManyToManyField(to='orders.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
