# Generated by Django 3.0.6 on 2020-06-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_topping',
            name='category',
        ),
        migrations.AddField(
            model_name='category_topping',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cat_topping',
            field=models.ManyToManyField(blank=True, to='orders.Category_Topping'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item_topping',
            field=models.ManyToManyField(blank=True, to='orders.Item_Topping'),
        ),
    ]
