# Generated by Django 3.0.6 on 2020-06-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200625_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_topping',
            name='price',
            field=models.FloatField(blank=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
